services:
  test-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: popcorn-palace-test
      POSTGRES_PASSWORD: popcorn-palace-test
      POSTGRES_DB: popcorn-palace-test
    ports:
      - '5433:5432' # Map to port 5433 on host to avoid conflict with dev database
    volumes:
      - test-db-data:/var/lib/postgresql/data
    networks:
      - test-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U popcorn-palace-test']
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  test-network:
    driver: bridge

volumes:
  test-db-data:
    driver: local
